Автоматическое сохранение проекта скриптом PS

diff --git a/19. Docker/Docker b/19. Docker/Docker
--- a/19. Docker/Docker
+++ b/19. Docker/Docker
@@ -2416,7 +2416,14 @@
 
     // CMD //
     //-----//
-    // -
+    // - Команда по умолчанию при запуске контейнера из этого образа.
+    // - Подоглавление
+    //
+    //    • Пояснения к ENTRYPOINT
+    //    • Пояснения к CMD
+    //    • CMD имеет 3 формы
+    //    • Примечания
+    //
 
       # Пояснения к ENTRYPOINT
         - Термином "entrypoint" называют обработчик по умолчанию.
@@ -2468,7 +2475,7 @@
         - Хоть мы и не указали bash после ubuntu, она выполнилась.
         - Потому что мы указали bash в кач-ве CMD в DockerFile.
 
-      # CMD имеет 3 формы:
+      # CMD имеет 3 формы
 
         • Exec-форма
           - Основной формат для CMD:
@@ -2525,33 +2532,466 @@
 
     // LABEL //
     //-------//
-    // -
+    // - Метаданные для образа в формате ключ=значение
+    // - В одном DockerFile можно использовать несколько LABEL.
 
-      
+      # Примеры применения LABEL
+
+        LABEL "com.example.vendor"="ACME Incorporated"
+        LABEL com.example.label-with-value="foo"
+        LABEL version="1.0"
+        LABEL description="This text illustrates \
+        that label-values can span multiple lines."
+
+      # Помните про ограничение 127 слоёв
+        - Каждый LABEL, как и другие инструкции, образует новый слой.
+        - Но при этом особой важности для образа не имеет.
+        - Большое кол-во LABEL можен тестолково потратить эти 127 мест.
+        - Эффективнее было бы впихнуть нужную информацию в 1-ин LABEL.
+        - Вот ещё примеры:
+
+            LABEL multi.label1="value1" multi.label2="value2" other="value3"
+            LABEL multi.label1="value1" \
+                  multi.label2="value2" \
+                  other="value3"
+
+      # Как посмотреть LABELS конкретного образа
+        - Для этого надо использовать команду docker inspect.
+        - Нужная информация будет в объекте с ключём "Labels".
 
     // EXPOSE //
     //--------//
-    // -
+    // - Информировать Docker'а, что контейнеру нужны такие-то порты
+    // - Внимание! Это НЕ открывает соответствующие порты для контейнера.
+    // - Открыть все "выставленные" порты можно флагом -P при docker run.
+    // - Пробросить любые порты при docker run можно флагом -p (p в нижнем регистре).
 
+      EXPOSE <port> [<port>...]
 
     // ENV //
     //-----//
-    // -
+    // - Назначить переменные среды для нижележащих инструций аля <key> <value>.
+    // - Можно в одной инструкции назначить от 1-й и более пар.
+    // - Их можно использовать в качестве переменных в нижележащих инструкциях.
 
+      # Форматы
+
+        • Формат №1
+          - Вся строка после <key> будет рассматриваться, как <value>
+
+              ENV <key> <value>
+
+        • Формат №2
+          - Можно указать сколько угодно пар <key>=<value> через пробел.
+
+              ENV <key>=<value> ...
+
+      # Примеры
+        - Ниже пара примеров, которые эквивалентны.
+        - 1-ый вариант предпочтительнее, он создаёт лишь 1 слой.
+
+            ENV myName="John Doe" myDog=Rex\ The\ Dog \
+                myCat=fluffy
+
+            ENV myName John Doe
+            ENV myDog Rex The Dog
+            ENV myCat fluffy
+
+      # ENV-переменные сохраняются у образа напостоянной основе
+        - Вот какой-то разработчик сделал образ.
+        - И у него в DockerFile был такой слой:
+
+            ENV DEBIAN_FRONTEND noninteractive
+
+        - Затем вы решили сделать свой образ на основе его образа.
+        - В вашем DockerFile доступна переменная DEBIAN_FRONTEND.
+        - И в запущенном из образа контейнере она тоже будет доступна.
+        - Если Вы её не заметите, то у вас apt-get работать нормально не будет.
+
+      # Посмотреть ENV-переменные образа можно через docker inspect
+        - Надо искать ключ "env".
+
+      # Изменить ENV-переменную при запуске можно ключём --env
+        - Например:
+
+            docker run --env <key>=<value>
 
     // ADD //
     //-----//
-    // -
+    // - Копирует файлы/каталоги из <src> в <dest> контейнера.
+    // - В качестве <src> могут быть локальные (path) и удалённые (url).
+    // - Подоглавление
+    //
+    //    • Форматы
+    //    • Wildcards в <src>
+    //    • Все новые файлы и каталоги создаются с UID == GID == 0
+    //    • Если <src> это URL
+    //    • Набор замечаний
+    //    • ADD подчиняется следующим правилам
+    //    •
+    //
+
+      # Форматы
+
+        • Формат №1
+          - Можно указать от 1 и больше <src> и один <dest>.
+          - Если <src> локальные, путь д.б. относительно корня контекста.
+
+              ADD <src>... <dest>
+
+          - <dest> м.б. абсолютным path.
+          - Или относительным с корнем в WORKDIR, куда источники будут скопированы.
+
+              ADD test relativeDir/          # adds "test" to `WORKDIR`/relativeDir/
+              ADD test /absoluteDir/         # adds "test" to /absoluteDir/
+
+        • Формат №2
+          - Эта форма для путей, содержащих пробелы.
+
+              ADD ["<src>",... "<dest>"]
+
+      # Wildcards в <src>
+        - Каждый <src> представляет glob-шаблон.
+        - Т.Е. можно применять всякие: * / ? / т.д.
+        - Всё это обрабатывается с помощью filepath.Math в GO.
+        - Например:
+
+            ADD hom* /mydir/        # adds all files starting with "hom"
+            ADD hom?.txt /mydir/    # ? is replaced with any single character, e.g., "home.txt"
+
+      # Все новые файлы и каталоги создаются с UID == GID == 0
+        - Сабж.
+
+      # Если <src> это URL
+
+        • Всё в <dest> будет иметь chmod 600.
+        • Если вернётся HTTP-заголовок Last-Modifyed
+          - Он будет использован для установки mtime файлов в <dest>.
+          - Однако, mtime не применяется для того, чтобы определить,
+            обновился ли файл, и надо ли обновить кэш.
+
+      # Набор замечаний
+
+        • Если DockerFile передаётся в docker build через STD IN
+          - В этом случае контекст полностью отсутствует.
+          - Поэтому в ADD могут быть лишь <src> с URL.
+          - Пример:
+
+              docker build - < somefile
+
+          - Кроме случая, когда передаётся архив.
+          - DockerFile должен лежать в корне этого архива.
+          - Всё остальное в нём будет рассматриваться в кач-ве контекста.
+          - Пример:
+
+              docker build - < archive.tar.gz
+
+        • Если <src> это URL требующий аутентификации
+          - Тогда надо использовать RUN wget / RUN curl / другой инструмент.
+          - Поскольку инструкция ADD не поддерживает аутентификацию.
+
+        • Замечание по поводу инвалидации кэша инструкцией ADD
+          - Кэш инвалидируется в случае изменения содержимого по адресу <src>.
+          - Кэш инвалидируется для всех последующих инструкций в Dockerfile.
+          - В том числе и для инструкции RUN.
+
+      # ADD подчиняется следующим правилам
+
+        • Локальный <src> не может быть абсолютным
+          - Это должен быть относительный локальный путь.
+          - В качестве root используется корень контекста.
+
+        • Если <src> URL, а <dest> НЕ заканчивается на /
+          - То файл из <src> просто копируется в <dest>.
+
+        • Если <src> URL, а <dest> заканчивается на /
+          - То имя для файла из <src> берётся из URL.
+          - И файл копируется по адресу <dest>/<filename>
+          - Например:
+
+              ADD http://example.com/foobar /
+
+          - Это создаст файл: /foobar
+          - Кроме того, URL в <src> должен иметь URI, отличный от /
+          - Например, такой URL не сработает, т.к. неоткуда брать <filename>:
+
+              http://example.com
+
+        • Если <src> является каталогом
+          - То весь контент каталога копируется.
+          - Включая метаданные файловой системы.
+          - Сам же каталог не копируется, только его содержимое.
+
+        • Если по адресу <src> находится архив
+          - Если это локальный path, архив будет распакован в <dest>.
+          - Если это URL, то архив НЕ будет распакован, а будет скопирован в <dest>.
+
+        • Если <src> это файл
+          - Он копируется индивидуально, в соотв. со своими метаданными.
+          - Плюс см.выше особенности, если <dest> заканчивается или нет на /
+
+        • Если указаны более 1-го <src>
+          - Не важно, прямо или с использованием wildcards.
+          - Тогда <dest> ОБЯЗАН быть каталогом и заканчиваться на /
+
+        • Если <dest> не заканчивается на /
+          - То он будет считаться обычным файлом.
+          - И содержимое <src> будет записано в этот файл <dest>.
+
+        • Если <dest> не существует
+          - Он будет автоматически создан.
 
 
     // COPY //
     //------//
-    // -
-
+    // - Аналог ADD, но без tar и URL возможностей.
 
     // ENTRYPOINT //
     //------------//
-    // -
+    // - Позволяет превратить контейнер в некий сервис.
+    // - Подоглавление
+    //
+    //    • Форматы
+    //    • Пояснения к ENTRYPOINT
+    //    • Превращение контейнера в сервис на примере
+    //    • Пояснения к CMD
+    //    • ENTRYPOINT м.б. перезаписана с помощью флага --entrypoint
+    //    • Только последняя инструкция ENTRYPOINT в DockerFile имеет силу
+    //
+    //    • Пример работы с exec-форматом ENTRYPOINT
+    //    • Пример работы с shell-форматом ENTRYPOINT
+    //
+
+      # Форматы
+
+        • Формат №1
+          - Это exec-формат, он является предпочтительным.
+          - Формат:
+
+              ENTRYPOINT ["executable", "param1", "param2"]
+
+        • Формат №2
+          - Это shell-формат (не рекомендуется).
+          - Предотвращает использование CLI-аргументов CMD и run.
+          - При этом ENTRYPOINT выполняется, как подкаманда /bin/sh -c
+          - А последний не передаёт никаких сигналов от ОС.
+          - То есть исполняемая не будет PID 1 контейнера.
+          - А значит, например, сигнал выключения контейнера docker stop <container>
+            не будут доходить.
+          - Формат:
+
+              ENTRYPOINT command param1 param2
+
+      # Пояснения к ENTRYPOINT
+        - Термином "entrypoint" называют обработчик по умолчанию.
+        - Изначально в Docker в качестве EP используется /bin/sh -c.
+        - И если запустить такой код:
+
+            docker run -i -t ubuntu bash
+
+              Здесь
+              • EP == /bin/sh
+              • Образ == ubuntu
+              • Команда == bash
+
+        - Поэтому bash будет запущен с помощью EP == /bin/sh.
+        - То есть, вот таким образом: /bin/sh -c bash
+        - Потом народ запросил возможность указывать другой EP.
+        - Появился параметр -entrypoint и инструкция ENTRYPOINT.
+
+      # Превращение контейнера в сервис на примере
+        - Исходная ситуация
+            • У нас есть образ с Redis.
+            • Его данные хранятсв volume вне образа.
+            • Мы хотим запросить данные из хранилища по ключу.
+            • Сейчас мы можем это сделать примерно так:
+
+                docker run redisimg redis -H something -u toto get key
+
+        - Упрощение с помощью ENTRYPOINT
+            • Берём и делаем в DockerFile такой EntryPoint:
+                ENTRYPOINT ["redis", "-H", "something", "-u", "toto"]
+            • Благодаря этому запрос из хранилища по ключу упростился:
+
+                docker run redisimg get key
+
+        - Рассмотрим повнимательнее, что именно здесь происходит.
+        - Каким образом будет формироваться итоговая команда:
+
+          • Сначала идёт: docker run <image>
+          • Потом аргументы из ENTRYPOINT: redis -H something -U toto
+          • Потом идёт то, что было справа от docker run <image>: get key.
+          • Итог: docker run redisimg redis -H something -U toto get key
+          • Иллюстрация:
+
+              docker run <image>   Аргументы из ENTRYPOINT    Аргументы команды
+              -------------------|--------------------------|------------------
+              docker run redisimg redis -H something -U toto get key
+
+      # Пояснения к CMD
+        - Выше мы узнали о существовании entrypoint по умолчанию.
+        - Но вот команды по умолчанию нет, это пустая строка.
+        - Но её можно задать с помощью инструкции CMD в DockerFile.
+        - Допустим, мы задали: CMD bash
+        - Тогда при выполнении:
+
+            docker run -i -t ubuntu
+
+              Здесь
+              • EP == /bin/sh
+              • Образ == ubuntu
+              • Команда == bash
+
+        - Хоть мы и не указали bash после ubuntu, она выполнилась.
+        - Потому что мы указали bash в кач-ве CMD в DockerFile.
+
+      # ENTRYPOINT м.б. перезаписана с помощью флага --entrypoint
+        - Например: docker run --entrypoint
+
+      # Только последняя инструкция ENTRYPOINT в DockerFile имеет силу
+        - Сабж.
+
+      # Пример работы с exec-форматом ENTRYPOINT
+
+        • Применяйте ENTRYPOINT для стабильных команд и аргументов
+          - Которые должны присутствовать при docker run всегда.
+          - А CMD для дополнительных, которые скорее всего заменяются.
+          - Например:
+
+              FROM ubuntu
+              ENTRYPOINT ["top", "-b"]
+              CMD ["-c"]
+
+          - Вот как это будет работать
+
+              docker run ubuntu             // Вызовет: docker run ubuntu top -b -c
+              docker run ubuntu -a          // Вызовет: docker run ubuntu top -b -a
+
+        • После запуска контейнера убедитесь, что top 1-нный процесс
+          - То есть он не является подпроцессом, скажем, /bin/sh
+          - А является единственным процессом, запущенном в контейнере.
+          - Пример:
+
+              docker run -it --rm --name test  top -H
+
+          - А для уже работающего контейнера:
+
+              docker exec -it test ps aux
+
+        • Следствием обладания PID == 1 является возможность получать сингналы
+          - Допустим в контейнере запущен 1 процесс top с PID == 1.
+          - Docker может послать контейнеру test сигнал docker stop test.
+          - Процесс top получит этот сигнал и мягко (gracefully) завершится.
+
+        • Пример запуска apache в фореграунд с PID == 1
+
+            FROM debian:stable
+            RUN apt-get update && apt-get install -y --force-yes apache2
+            EXPOSE 80 443
+            VOLUME ["/var/www", "/var/log/apache2", "/etc/apache2"]
+            ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
+
+        • Как в скрипте убедиться, что final executable получает unix-сигналы
+          - С помощью команд exec и gosu.
+          - Например:
+
+              #!/bin/bash
+              set -e
+
+              if [ "$1" = 'postgres' ]; then
+                  chown -R postgres "$PGDATA"
+
+                  if [ -z "$(ls -A "$PGDATA")" ]; then
+                      gosu postgres initdb
+                  fi
+
+                  exec gosu postgres "$@"
+              fi
+
+              exec "$@"
+
+        • Можно даже повесить хук на завершение работы
+          - Допустим вы запустили контейнер со своей bash-программой.
+          - И в случае получения сигнала завершения надо сделать некую работу.
+          - Что-нибудь подчистить, например, или провзаимодействовать с другими контейнерами.
+          - Тогда следует убедиться в том, что скрипт в ENTRYPOINT получает unix-сигналы,
+            пропускает их, и выполняет некую работу.
+          - Пример:
+
+              #!/bin/sh
+              # Note: I've written this using sh so it works in the busybox container too
+
+              # USE the trap if you need to also do manual cleanup after the service is stopped,
+              #     or need to start multiple services in the one container
+              trap "echo TRAPed signal" HUP INT QUIT KILL TERM
+
+              # start service in background here
+              /usr/sbin/apachectl start
+
+              echo "[hit enter key to exit] or run 'docker stop <container>'"
+              read
+
+              # stop service and clean up here
+              echo "stopping apache"
+              /usr/sbin/apachectl stop
+
+              echo "exited $0"
+
+        • Ряд замечаний
+
+          • Можно перезаписать ENTRYPOINT с помощью флага --entrypoint
+            - Во время использования docker run.
+            - В этом случае будет использовать exec-формат ENTRYPOINT.
+
+          • Exec-формат парсится, как JSON-массив
+            - Поэтому везде надо использовать '' вместо "".
+
+          • В отличии от shell-формата, exec-формат не запускает командную оболочку
+            - Это означает, что обычного оболочечного процесса не происходит.
+            - Для примера рассмотрим:
+
+                ENTRYPOINT [ "echo", "$HOME" ]
+
+            - Никакой подстановки значения $HOME не произойдёт.
+            - Чтобы оболочечный процесс сработал, надо вручную вызвать оболочку.
+            - Например:
+
+                ENTRYPOINT [ "sh", "-c", "echo", "$HOME" ]
+
+            - Однако подстановка ENV-переменных будуте производиться
+              в любом случае парсером DockerFile.
+
+      # Пример работы с shell-форматом ENTRYPOINT
+
+        • В качестве ENTRYPOINT можно указать обычную строку
+          - Тогда будет запущен процесс /bin/sh -c
+          - И эта строка будет исполнена в нём.
+          - Любые аргументы из CMD и docker run будут проигнорированы.
+
+        • Лучше начинать с exec
+          - Рассмотрим пример:
+
+              FROM ubuntu
+              ENTRYPOINT exec top -b
+
+          - И запустим его:
+
+              docker run -it --rm --name test top
+
+          - Мы увидим лишь 1 процесс top с PID == 1.
+          - При поступлении сигнала завершения от Linux от мягко завершится.
+          - Но если забыть указать "exec" в "exec top -b", например:
+
+              FROM ubuntu
+              ENTRYPOINT top -b
+              CMD --ignored-param1
+
+          - То в top будут 2 процесса: /bin/sh с PID == 1, и top.
+          - В этом случае все сигналы от Linux будет получать /bin/sh.
+          - В результате завершать процесс top мягко будет невозможно.
+          - Top будет завершаться жёстко после таймаута при поступлении
+            от Linux сигнала завершения в /bin/sh.
+
 
 
     // VOLUME //
